[0001].[2021.04.03.01.53.03.394331].SRV1.INF:Main.py.<module>.316:Main Program Started
[0002].[2021.04.03.01.53.03.399334].SRV1.ERR:Main.py.<module>.319:Artificial Error Message for testing purpose
[0003].[2021.04.03.01.53.03.403336].SRV1.INF:Main.py.<module>.320:Command Line iniFileName=default.ini
[0004].[2021.04.03.01.53.03.407339].SRV1.INF:Main.py.<module>.322:Command Line VerboseMode=None
[0005].[2021.04.03.01.53.03.411342].SRV1.INF:Main.py.<module>.325:AppSpoManager.DebugVerboseModeOn=True
[0006].[2021.04.03.01.53.03.415344].SRV1.INF:Main.py.<module>.326:AppSpoManager.DebugInfoMessages=True
[0007].[2021.04.03.01.53.03.420348].SRV1.INF:Main.py.<module>.327:AppSpoManager.DebugErrorMessages=True
[0008].[2021.04.03.01.53.03.425351].SRV1.INF:Main.py.<module>.328:AppSpoManager.DebugTargetConsole=False
[0009].[2021.04.03.01.53.03.430354].SRV1.INF:Main.py.<module>.329:AppSpoManager.DebugTargetFile=True
[0010].[2021.04.03.01.53.03.434357].SRV1.INF:Main.py.<module>.330:AppSpoManager.DebugTargetFilePath=Debugs\Debug1
[0011].[2021.04.03.01.53.03.438361].SRV1.INF:Main.py.<module>.331:AppSpoManager.DebugLinesPerFile=1000
[0012].[2021.04.03.01.53.03.442362].SRV1.INF:Main.py.<module>.332:AppSpoManager.AppRunFolder=c:\Apps\PythonTry1
[0013].[2021.04.03.01.53.03.446365].SRV1.INF:Main.py.<module>.355:ModuleFileNameOnly=Main.py
[0014].[2021.04.03.01.53.03.451367].SRV1.INF:Main.py.<module>.363:File=c:\Apps\PythonTry1\Main.py
[0015].[2021.04.03.01.53.03.459373].SRV1.INF:Main.py.<module>.364:FileDirName=c:\Apps\PythonTry1
[0016].[2021.04.03.01.53.03.466377].SRV1.INF:Main.py.<module>.365:FileAbsPath=c:\Apps\PythonTry1\Main.py
[0017].[2021.04.03.01.53.03.471381].SRV1.INF:Main.py.<module>.368:ModuleName1=__main__
[0018].[2021.04.03.01.53.03.476384].SRV1.INF:Main.py.<module>.369:ModuleName2=Main
[0019].[2021.04.03.01.53.03.481387].SRV1.INF:Main.py.<module>.378:Main Program Started
[0020].[2021.04.03.01.53.03.485392].SRV1.INF:Main.py.<module>.379:Python Executable Path=C:\Program Files\Python39\python.exe
[0021].[2021.04.03.01.53.03.490393].SRV1.INF:Main.py.<module>.380:Python Interpreter Version=3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[0022].[2021.04.03.01.53.03.498399].SRV1.INF:Main.py.<module>.383:Sys.Path=['c:\\Apps\\PythonTry1', 'C:\\Program Files\\Python39\\python39.zip', 'C:\\Program Files\\Python39\\DLLs', 'C:\\Program Files\\Python39\\lib', 'C:\\Program Files\\Python39', 'C:\\Users\\user2\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Program Files\\Python39\\lib\\site-packages']
[0023].[2021.04.03.01.53.03.537425].SRV1.INF:Main.py.<module>.430:Showing MainWindow
[0024].[2021.04.03.01.53.05.644756].SRV1.INF:Main.py.actionDebugTest1Handler.154:192.168.0.1, KAT1.ODA1, KORÝDOR DUVAR
192.168.0.2, KAT2.ODA2, TAVAN HOPARLÖR
192.168.0.3, KAT3.ODA3, KAPI_ÖNÜ_ANANS
[0025].[2021.04.03.01.54.38.725987].SRV1.INF:Main.py.actionDebugTest1Handler.166:Node[0]=0=[0] 1=192.168.0.1, KAT1.ODA1, KORÝDOR DUVAR]
[0026].[2021.04.03.01.54.38.733994].SRV1.INF:Main.py.actionDebugTest1Handler.166:Node[1]=0=[1] 1=192.168.0.2, KAT2.ODA2, TAVAN HOPARLÖR]
[0027].[2021.04.03.01.54.38.740997].SRV1.INF:Main.py.actionDebugTest1Handler.166:Node[2]=0=[2] 1=192.168.0.3, KAT3.ODA3, KAPI_ÖNÜ_ANANS]
